version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: personal_tracker_db_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SECRET}
      POSTGRES_DB: TrackerDbTest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

